### ISSUE TITLE
FISABIO Level check 3 issue

### ISSUE THREAD

**Issue by elisacm98** [UMC-Utrecht-RWE/ConcePTION-Level3#1]
Good morning,

We have been running Level check 3, but we have run into a problem with the Study_source_population file. Specifically, when we try to run the fisrt script (study_source_population_script.R), we get an error in Step_Report_01_12_Visits.R. The file stops at l.102 and we get the error "Agebands do not match".  I have been searching the problem and in the previous steps two different dataframes are created: COUNT and PT1.  Each one of them has a different ageband, so that in PT1 the last age group is "100+" and in COUNT there are two age groups after 100 years old: 100-109 and 110-119. 

We hope you can help us to solve this issue. Thank you very much in advance.

**Comment by elisacm98** [comment]
Hi,

It appeared an error and not a warning because I was executung an old version of the L3 scripts. I've downloaded the scripts again and now I'm executing the correct version. Script study_source_population_script.R has run perfectly.

However, now we have problems creating the reports. Report_02_Dates.Rmd has been created, but the others no. In both of them we have the same error: 

Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L,  : 
  invalid value 0 for 'digits' argument

Specifically, the problematic function is Line_plot2 and I think that the line that generates the error is line 243 in FUNCTIONS.R file:

 if(ceiling(max(MATRIX)) >= 10)t <- format(seq(from = 0,to = ceiling(max(MATRIX)),length.out = 11),digits = 0)

Could you please helps us to solve this issue? Thank you in advance.

**Comment by relbersumcu** [comment]
@elisacm98  @t-andresvaz 

Line_plot2 is not used anymore in the most recent scripts. It is replaced by ggploty(ggplot) to add hover functionality.

If I do a control-F in https://github.com/UMC-Utrecht-RWE/ConcePTION-Level3/blob/main/Level_3_to_be_deployed1.0/p_steps/Report_02_Dates.Rmd with "Line_plot2" I do only find this commented out

**Comment by relbersumcu** [comment]
1. Can you please verify in which script
2. If we know in which script it would be optimal if you could provide the input file. If by example row 153 of the script produces the error the input file would be ..._R_01_0608_DT_op_start_date_PLOT.rds. With this file the issue can easily be reviewed.
