### ISSUE TITLE
Function Line_plot2 error

### ISSUE THREAD

**Issue by t-andresvaz** [UMC-Utrecht-RWE/ConcePTION-Level3#2]
problems creating the reports. Report_02_Dates.Rmd has been created, but the others no. In both of them we have the same error:

Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L, :
invalid value 0 for 'digits' argument

Specifically, the problematic function is Line_plot2 and I think that the line that generates the error is line 243 in FUNCTIONS.R file:

if(ceiling(max(MATRIX)) >= 10)t <- format(seq(from = 0,to = ceiling(max(MATRIX)),length.out = 11),digits = 0)

Could you please helps us to solve this issue? Thank you in advance.

**Comment by t-andresvaz** [comment]
Hi @elisacm98 , 
from @relbersumcu 

Line_plot2 is not used anymore in the most recent scripts. It is replaced by ggploty(ggplot) to add hover functionality.

If I do a control-F in https://github.com/UMC-Utrecht-RWE/ConcePTION-Level3/blob/main/Level_3_to_be_deployed1.0/p_steps/Report_02_Dates.Rmd with "Line_plot2" I do only find this commented out

1. Can you please verify in which script
2. If we know in which script it would be optimal if you could provide the input file. If by example row 153 of the script produces the error the input file would be ..._R_01_0608_DT_op_start_date_PLOT.rds. With this file the issue can easily be reviewed.

**Comment by elisacm98** [comment]
Hi,

I have problems creating Report_01_StudyPopulation and Report_03_VisitsLifestyle. In this scripts the function Line_plot2 is not commented out. Report_02_Dates was created perfectly.

In Report_01_StudyPopulation the input files that produces the error are:
-  ALL_R_01_02_CompareToSource.csv
- ALL_R_01_05_STUDYPOPPY2.csv 
-  ALL_R_01_11_InDatabaseDuration.csv.

In Report_03_VisitsLifestyle the file that produces the error are:

- ALL_R_01_12_VISITS.csv

As I told you before, the error that appears is always the same: 

Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L,  : 
  invalid value 0 for 'digits' argument

**Comment by t-andresvaz** [comment]
Yes, I found the Line_plot2 reference in both files. 
Report_01_StudyPopulation and Report_03_VisitsLifestyle

To fix, we need to implement changes in the source code to use ggploty(ggplot) instead.
Example as reference to implement geplot is in file Report_02_Dates.

Created new branch for this fix here:
(https://github.com/UMC-Utrecht-RWE/ConcePTION-Level3/tree/2-function-line_plot2-error)  

This issue will be closed after merging the fix to main branch.

**Comment by relbersumcu** [comment]
I would rather fix the Line_plot2. Earlier I tried to use the ggploty(ggplot) but I never succeded in getting the appearences nicely

**Comment by elisacm98** [comment]
Hi,

Here is the data you requested:
[ALL_R_01_02_CompareToSource.csv](https://github.com/UMC-Utrecht-RWE/ConcePTION-Level3/files/9130376/ALL_R_01_02_CompareToSource.csv)

**Comment by elisacm98** [comment]
Hi,

I've read the issue you mentioned and I changed the code line as you suggested. Now I can create the Reports. Thank you so much for your help.

**Comment by relbersumcu** [comment]
@elisacm98 thanks for the help. I did also apply the change in the code.
@t-andresvaz can we close this issue? Since it was a very minor change I changed it diretly in the main, is that ok for these sitiutions?

**Comment by t-andresvaz** [comment]
Yes, it works! I will close this issue.
In parallel, I will ask to test and close issue #4 with this  same fix.
