### ISSUE TITLE
Folder 'populations' doesn't exist in 'g_intermediate'

### ISSUE THREAD

**Issue by bpoblador** [UMC-Utrecht-RWE/ConcePTION-Level3#3]
I obtain the error
In gzfile(file, mode) : 
cannot open compressed file '/pfizer/Data characterisation/Level_3_to_be_deployed1.0/g_intermediate/populations/ALL_study_population.rds', probable reason 'No such file or directory'

It's because the 'populations' folder doesn't exist in g_intermediate when the code is downloaded.  If you create the folder the running continues.

**Comment by acidroyo-UMCU** [comment]
Hello @bpoblador , thank you for approaching us and providing already a solution. We will fix this issue for the upcoming release.

-----
For now, until the next release of the code, the solution to this issue is as follows:

> It's because the 'populations' folder doesn't exist in g_intermediate when the code is downloaded. If you create the folder the running continues.
