### ISSUE TITLE
Error creating Report_01_StudyPopulation

### ISSUE THREAD

**Issue by anallg** [UMC-Utrecht-RWE/ConcePTION-Level3#4]
@t-andresvaz @relbersumcu @acidroyo-UMCU 
After execute study_source_population_script.R during more than 24h we have the following error:

label: unnamed-chunk-6 (with options) 
List of 3
 $ echo     : logi FALSE
 $ fig.show : chr "hold"
 $ out.width: chr "50%"

Quitting from lines 278-368 (Report_01_StudyPopulation.Rmd) 
 Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L, : 
invalid value 0 for 'digits' argument
25.
prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L, 
na.encode, scientific, decimal.mark)), big.mark = big.mark, 
big.interval = big.interval, small.mark = small.mark, small.interval = small.interval, 
decimal.mark = decimal.mark, input.d.mark = decimal.mark, ...
24.
format.default(seq(from = 0, to = ceiling(max(MATRIX)), length.out = 11), 
digits = 0)
23.
format(seq(from = 0, to = ceiling(max(MATRIX)), length.out = 11), 
digits = 0) at FUNCTIONS.R#243
22.
Line_plot2(MATRIX = TEMP2, title = "Relative decline", x.l = "Year_op_start_date", 
y.l = "Percentage of lost PY", color = colors, leg = F, l.size = 1.2, 
tck.size = 1, x.las = 1) at <text>#28
21.
eval(expr, envir, enclos)
20.
eval(expr, envir, enclos)
19.
eval_with_user_handlers(expr, envir, enclos, user_handlers)
18.
withVisible(eval_with_user_handlers(expr, envir, enclos, user_handlers))
17.
withCallingHandlers(withVisible(eval_with_user_handlers(expr, 
envir, enclos, user_handlers)), warning = wHandler, error = eHandler, 
message = mHandler)
16.
handle(ev <- withCallingHandlers(withVisible(eval_with_user_handlers(expr, 
envir, enclos, user_handlers)), warning = wHandler, error = eHandler, 
message = mHandler))
15.
timing_fn(handle(ev <- withCallingHandlers(withVisible(eval_with_user_handlers(expr, 
envir, enclos, user_handlers)), warning = wHandler, error = eHandler, 
message = mHandler)))
14.
evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos, 
debug = debug, last = i == length(out), use_try = stop_on_error != 
2L, keep_warning = keep_warning, keep_message = keep_message, 
output_handler = output_handler, include_timing = include_timing)
13.
evaluate::evaluate(...)
12.
evaluate(code, envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning), 
keep_message = !isFALSE(options$message), stop_on_error = if (is.numeric(options$error)) options$error else {
if (options$error && options$include) 
0L ...
11.
in_dir(input_dir(), expr)
10.
in_input_dir(evaluate(code, envir = env, new_device = FALSE, 
keep_warning = !isFALSE(options$warning), keep_message = !isFALSE(options$message), 
stop_on_error = if (is.numeric(options$error)) options$error else {
if (options$error && options$include) ...
9.
eng_r(options)
8.
block_exec(params)
7.
call_block(x)
6.
process_group.block(group)
5.
process_group(group)
4.
withCallingHandlers(if (tangle) process_tangle(group) else process_group(group), 
error = function(e) {
setwd(wd)
cat(res, sep = "\n", file = output %n% "") ...
3.
process_file(text, output)
2.
knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
1.
rmarkdown::render(paste0(pre_dir, "Report_01_StudyPopulation.Rmd"), 
output_file = paste0(report_dir1, "/", "Report_01_Study_population_", 
i, ".html"), output_dir = report_dir1)

**Comment by relbersumcu** [comment]
This issue is related to #2 
I cannot reproduce but there have been a change in the format function recently.
In the following script there is a line with the function format. 0 is not allowed anymore.

[
](https://github.com/UMC-Utrecht-RWE/ConcePTION-Level3/blob/cc329a39e8b819faf6d22d9355a564a35c797855/Level_3_to_be_deployed1.0/p_steps/functions/FUNCTIONS.R#L243)


Can you try to change this line  like this: 
if(ceiling(max(MATRIX)) >= 10)t <- format(seq(from = 0,to = ceiling(max(MATRIX)),length.out = 11),digits = 0)
To
if(ceiling(max(MATRIX)) >= 10)t <- format(seq(from = 0,to = ceiling(max(MATRIX)),length.out = 11),digits = 1)

**Comment by anallg** [comment]
@relbersumcu I´m trying to run only from 
for(i in readRDS(paste0(std_pop_tmp,"SCHEME_06.rds"))[["subpopulations"]]){

After system.time(source(paste0(pre_dir,"study_source_population_script.R")))
but I have the following issue: 
Quitting from lines 60-98 (Report_01_StudyPopulation.Rmd) 
Error in POP_TREE(m = TEMP, xlabel = "Percentage", offset = 2, linewidth = 15,  : 
  could not find function "POP_TREE"

Please, can you help me? I cant understand where is defined POP_TREE. The reason is to avoid the full execution again because it takes more than 24h :|

**Comment by relbersumcu** [comment]
@anallg @t-andresvaz 
See #2
With that fix also this issue should be fixed

**Comment by t-andresvaz** [comment]
@anallg please, could you confirm that the solution for issue #2 also fixed this issue and close it?

**Comment by anallg** [comment]
This is issue is solved
