### ISSUE TITLE
Solved error in Report_09_VACCINES_Overview_Completeness_L3.Rmd

### ISSUE THREAD

**Issue by anallg** [UMC-Utrecht-RWE/ConcePTION-Level3#7]
@t-andresvaz @relbersumcu @acidroyo-UMCU 

Hello, we have the following problem running vaccines in Level 3. It seems is triyng to read a file that doesn´t exists. I think it´s necessary to change this part of the code: 

if (subpopulations_present=="No"){
description_vx<-fread(paste0(vacc_dir,"Masked/", list.files(paste0(vacc_dir, "Masked/"),"vaccines_description_masked.csv")))
datatable(description_vx, options = list(scrollX=T))
} else {
  description_vx<-fread(paste0(vacc_dir,subpopulations_names[a], "/Masked/", #
      list.files(paste0(**vacc_dir**,subpopulations_names[a],"/Masked/"),
        paste0(subpopulations_names[a],"_vaccines_description_masked.csv"))))
datatable(description_vx, options = list(scrollX=T))
}

There is a bug in the code(line 90 aprox) and it´s calling to med_dir here and don´t to vacc_dic. 

This is the original error: 

Quitting from lines 91-98 (Report_09_VACCINES_Overview_Completeness_L3.Rmd) 
 Error in fread(paste0(vacc_dir, subpopulations_names[a], "/Masked/", list.files(paste0(med_dir, : 
File 'G:/ConcePTION/ROC20/QC/ConcePTION-Level3-main/g_output/VACCINES/PC/Masked/' is a directory. Not yet implemented.
24.
stop("File '", file, "' is a directory. Not yet implemented.")
23.
fread(paste0(vacc_dir, subpopulations_names[a], "/Masked/", list.files(paste0(med_dir, 
subpopulations_names[a], "/Masked/"), paste0(subpopulations_names[a], 
"_vaccines_description_masked.csv")))) at <text>#5
22.
eval(expr, envir, enclos)
21.
eval(expr, envir, enclos)
20.
eval_with_user_handlers(expr, envir, enclos, user_handlers)
19.
withVisible(eval_with_user_handlers(expr, envir, enclos, user_handlers))
18.
withCallingHandlers(withVisible(eval_with_user_handlers(expr, 
envir, enclos, user_handlers)), warning = wHandler, error = eHandler, 
message = mHandler)
17.
handle(ev <- withCallingHandlers(withVisible(eval_with_user_handlers(expr, 
envir, enclos, user_handlers)), warning = wHandler, error = eHandler, 
message = mHandler))
16.
timing_fn(handle(ev <- withCallingHandlers(withVisible(eval_with_user_handlers(expr, 
envir, enclos, user_handlers)), warning = wHandler, error = eHandler, 
message = mHandler)))
15.
evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos, 
debug = debug, last = i == length(out), use_try = stop_on_error != 
2L, keep_warning = keep_warning, keep_message = keep_message, 
output_handler = output_handler, include_timing = include_timing)
14.
evaluate::evaluate(...)
13.
evaluate(code, envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning), 
keep_message = !isFALSE(options$message), stop_on_error = if (is.numeric(options$error)) options$error else {
if (options$error && options$include) 
0L ...
12.
in_dir(input_dir(), expr)
11.
in_input_dir(evaluate(code, envir = env, new_device = FALSE, 
keep_warning = !isFALSE(options$warning), keep_message = !isFALSE(options$message), 
stop_on_error = if (is.numeric(options$error)) options$error else {
if (options$error && options$include) ...
10.
eng_r(options)
9.
block_exec(params)
8.
call_block(x)
7.
process_group.block(group)
6.
process_group(group)
5.
withCallingHandlers(if (tangle) process_tangle(group) else process_group(group), 
error = function(e) {
setwd(wd)
cat(res, sep = "\n", file = output %n% "") ...
4.
process_file(text, output)
3.
knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
2.
render(paste0(pre_dir, "/Report_09_VACCINES_Overview_Completeness_L3.Rmd"), 
output_dir = paste0(output_dir, "VACCINES/"), output_file = paste0(format(Sys.Date(), 
"%Y"), format(Sys.Date(), "%m"), format(Sys.Date(), "%d"), 
"_", data_access_provider_name, "_", subpopulations_names[a], ...
1.
system.time(render(paste0(pre_dir, "/Report_09_VACCINES_Overview_Completeness_L3.Rmd"), 
output_dir = paste0(output_dir, "VACCINES/"), output_file = paste0(format(Sys.Date(), 
"%Y"), format(Sys.Date(), "%m"), format(Sys.Date(), "%d"), 
"_", data_access_provider_name, "_", subpopulations_names[a], ...

**Comment by t-andresvaz** [comment]
thanks @anallg , it seems it fixes also issue #5
